apiVersion: ENC[AES256_GCM,data:0tw=,iv:yAXcHf55haqEoCupmse4hiLuCl31NGxI3oH9ReMVviA=,tag:bKqOSsPmOdJsRBJFQO07+g==,type:str]
data:
    token: ENC[AES256_GCM,data:j8wTZ4eZigLNU2AV4Aw/wu+fUY5w8Bk1wR6gCtyF8itRtiW2zKn1yJqH7Z5x/U8rAHSUSWqOA9yyWRoYfslTwQbND/X8Y3Kpo0PUgcjN7tdKfb2ytxiSDL1oXRCs0dSIlX9THfSr+gZVCkWRtquD/oJ8jydpc+Qw1yYJspNvc3rQ9bqPuTv1W/jzcVRhVFL8vX7zhGZFpNfpcCI9AVbqvpYH4sL7TikV57ew0Jjoibnh0ye5shwyx4uj5efNsXEaAZmY0kxyMC+k8Ait+U1Y3uNsO5b95EL7vMeDfU6fGjaVWS87eF0DsjQ0r1YG3lqfBuyuNyXdyIgtprp7dAlqPMFJ0Y7Yh4uUHofy9+LZL3nDgRGkfaTnTg2OsD1XOZL7eR8veU4uXru/jPzwKQVGT9SjFJ/8+xLdRm6T4iv7WBizLJqeBwknADNxzRA=,iv:QsaT8rq3ydlA7+uYUMelpnq8wGmYDWEjZMGVknk7IIs=,tag:6pP4Z0dO84PvMj0+lLaxJw==,type:str]
kind: ENC[AES256_GCM,data:SXQ2XVOy,iv:iJr2zw91z7WsSZCnt2v0epRsj0yNmGVoS9siMykRCk8=,tag:elr5n7FYxWyBw72K70dUUQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XWtkzrzKKadpFxiUWzJAzDYeHEi3xBai,iv:CJo8rBr9+7A5ht8JoygB5+6c4tHLDRz/92GYcKCMrns=,tag:cRIf6qXU1NjhQFDRVYOyEA==,type:str]
    namespace: ENC[AES256_GCM,data:hK0RN0GaUbLWHA==,iv:ZXGWmZvcLF/2tB/6PULdY3xSF0Rja2vmN2iU2GTH5eM=,tag:rwRKyQqQyRIN+ot8q04Lwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z1I1czk2RDZ5dGJhbE80
            TWJhOVVVOTNwSmlpeHhPUFJyd1FWWCsrY0E4CnI1UVg2VmQzUTAxWW96NGVVbnZu
            d3pPZG9qc2FCYzdNMjhrbk9hZDhCekUKLS0tIHVvRTlFcC94THlRQ1JCMDFNRVN6
            UnAwM0FGYTNDN2l0eG9oMkNqSWtrbkUKbSEgc7TyrRvbJSG9ZTLOAAO0YM8T2MiL
            qNUChY2H/eDMPHha0f2S0yGMBJ09ojw22QZlVgrL0HzZCwIVGo9vWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zt8e5n3g6dc4962jaggnhvq37e9yge42agyqncss5fy9kd3g0g5q23p6nf
    lastmodified: "2026-09-14T14:23:58Z"
    mac: ENC[AES256_GCM,data:4GoY4fr7PtB7/7ngAsAI0VLGtoYoPGMCJ1goO1YnZ/+HEopRTFqI05NidODV2DDRPS52TgXO9G1x9zJvNcOLK6k3hG4xRqK4vHugmahc07UupYB+og7x0PeOZu99QvDT6y8eHm0SaKdTXxDGG+5393/tTMUTX2vKVF/3YD8al6c=,iv:z/++dBVZnyHea5agktnXnAWs4WAlp6SVUwOQtPzPFOU=,tag:uP4JCBRQ+a8r/2h7klPeSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
