apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-repositories.yaml
  - helm-releases.yaml
configMapGenerator:
  - name: kube-prometheus-stack-values
    files:
      - values.yaml=kube-prometheus-stack-values.yaml
  - name: tempo-values
    files:
      - values.yaml=tempo-values.yaml
  - name: opentelemetry-collector-values
    files:
      - values.yaml=opentelemetry-collector-values.yaml
  - name: loki-values
    files:
      - values.yaml=loki-values.yaml
  - name: alloy-values
    files:
      - values.yaml=alloy-values.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
