apiVersion: v1
kind: Service
metadata:
  name: otel-go-downstream
  namespace: lab
  labels:
    app: otel-go-downstream
spec:
  selector:
    app: otel-go-downstream
  ports:
    - name: http
      port: 8080
      targetPort: http
