apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-go-downstream
  namespace: lab
  labels:
    app: otel-go-downstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-go-downstream
  template:
    metadata:
      labels:
        app: otel-go-downstream
    spec:
      containers:
        - name: otel-go-downstream
          image: guiosoft/otel-go-demo:dev
          imagePullPolicy: Never
          env:
            - name: SERVICE_NAME
              value: otel-go-downstream
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 24Mi
            limits:
              cpu: 200m
              memory: 128Mi
