apiVersion: ENC[AES256_GCM,data:6SU=,iv:qevybimQCNHh1xFilZQKasXflCBPkSP4IqIwvgFtfYo=,tag:TBMS8DsbjpK0tsKhNnXLnw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:8FeAcH4e9KiY01mIINhf7orhtJSP+dSglK+2IJIv638qLMoZU0bbevYK7ejd7KJjidNATW2c3Jdap1NoWZgQqMTwW9x++QDll1LoyS8Al94BO/S0CLD9O8rE0zTA+WsstieEYnrNsEfZDHSWcYOBsgb5Ol7V2HNCxHoWbo/35PbAjQGFbeuaq78EXtMXIgSuksrwpq025zOqkybXFf2e5pmvOJtgEIocUfk9MfFaG8see8sWuEiATYSrl40pps9gTGVlDUnL13z9r1bCTv5zup47A4YP/f/lQRRVn1TzkmDa8yBWlfBS7J7yU6D9AsjX,iv:dnf9p4a9ZHsHA3w1Bhu05Fd1snNQcVQCCrO1NXfAKI4=,tag:2d4X4ZjoPkFpI4hWwqPY3g==,type:str]
kind: ENC[AES256_GCM,data:I8q5iCWz,iv:QYeaPTLW+3GVwRUDrWOcios8cevMVXgmm24VbubQAd0=,tag:QzYPfBe2Y7AiKiacxoqLOQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:R6j4sjzB0k8v,iv:/ofHn8pgjdQlUjBo3itNXuxlp2QU7CnWWK38ryunb1M=,tag:IRRBzYfiF7Sd0pVgsp2HEA==,type:str]
    namespace: ENC[AES256_GCM,data:lq9NP3QWOCur1jo=,iv:vsP7bqyHsitL7GPdkQeuapTjRfvnc3+Odj9Ove1sysg=,tag:UaVm6xvwLbgh/OTl6ivkBw==,type:str]
type: ENC[AES256_GCM,data:1eZZ5pTvWwYHERqqzxTzSrqiiq92ohF7uWcHYBdE,iv:HTEc1haexrJVeinSie1VnB/cWtQr8QJ2uioKsydRsq4=,tag:nbPCFy80uCmPaT6DBiUBaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRDRBMmxkMVJyaEExL2lF
            UWFmL1RaTDU4eVBNVThwUWRNb1F3c3hOVkdNCkpqYXcwVXJvS3FSSjNlM0RQVWRB
            T1Z5aWdPQTY5UUN3ejNUeWUzQUFZd3MKLS0tIGtHV2RLUlIySlM4b2JwWjVNWkVK
            NCtIYjhqaDR3L25ZV0tyYnVvajVXNjAKah7OMzwVEeVB2us9sLAX12d3IY4eakZb
            k9YxPEKFhy5jfyu8RKqybEjZKXdNEPljzjrxaNx4WzZn3YgjkLAzPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zt8e5n3g6dc4962jaggnhvq37e9yge42agyqncss5fy9kd3g0g5q23p6nf
    lastmodified: "2026-10-05T15:12:34Z"
    mac: ENC[AES256_GCM,data:GiIc5VLRCfCnq7iorLQBruFuit6IjopDitzLkW3eCs0ccxzWdXNrudry08DIiUn8hVCHM1ZMicp9sF1RSJmDjlMjm6LTEIuH02vNu/zXtAihA4GXwhPqFDhvldqXxhhMozEpq6myouShQiMt1xE5i1bMm4KHOF42o+bwOMzR4+I=,iv:EzpMm9OdTvD1ENzxD0A4qOo6no+W5ODueo/7VcgsSog=,tag:o3hlWbt99iW/yS1Xl9kfFA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
