apiVersion: ENC[AES256_GCM,data:hBU=,iv:FnuxxZaFvCTDy4LgOB/HZz6LZrtpnHj9CF2yCHcynR0=,tag:CKzUNWKtgE6cElkHpZSDYQ==,type:str]
kind: ENC[AES256_GCM,data:sjLhuh40,iv:GqDvQMxHTdsKVvnxj7sb9ZJE3tzIDfzN7Rip8kVM17w=,tag:iiaM/5BgUR4p4hMulCZ+TQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Kwr7tBLAZCXg4ogZynUxBrUZkw==,iv:yDd1fSZrSgjzshW74lak6ppgHbhoQfEiUmH4UWSR2NI=,tag:ZDWthpJgnd0VT38pfoFeqA==,type:str]
    namespace: ENC[AES256_GCM,data:q2seiBm5IemSns0=,iv:YrCKnqSevHpG7c4j4ht5o1EwyiHYGUIYj/enhPmOPPw=,tag:GGfb/NxwW86EN7DbdFd6AA==,type:str]
type: ENC[AES256_GCM,data:WAXZOaWd,iv:Q4EhE7S8HwESPkSQOdJ37n07BYdm1H939rp/Gjc/Awc=,tag:jaDui4UQNP6SXRJ46q3vCg==,type:str]
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:XEybfjhXI8lrd8MnOCnIstZfALAodTEX/eIlcX9Gr9gm2UifrjRHjGbdHwFxQ6Q4,iv:lr5VaXzGuWQ7ni5p0pdaZoQJiAg1afJaMriNwJ7kchg=,tag:cxfsXtaqIRBsMWLq2NI4bQ==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:rvqzY4P8z1EMj0O4rEYDClRCJQ8JaFKbF1uCcKpKzYICj083Pd4EoUDaBtcIPKh1,iv:0aAhh54m7SIrBQoFI0JjnisFfsSut2QS+5XFN+5251E=,tag:eaODx8cn6SvQl39TyMOdqw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:mOZTvpp88xOsuteuPS76j1NMQ0lUyrj2fl2oJPokd7o2f70PuV68avpZdJ2x0WUrTQyZLVMUDmRFL+VNCmEdSb3OXAYLAjaaouf1aQIHSAoGQ3NtbH25nPNYEzkh1Oy5gaFpjWYtdIyq7dC4O9081O1eLPrpu+bKW2AhBEFnLP0UX6filAKfkvub,iv:ps7fiEWWymEYMWOSOKZjdm+c3nyJG9zq/4WPI0wDtKc=,tag:Hii1mYSAcg8Wq0ldWRazYQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:DB4Twb2NdN4JecWwLg6A7eGRpLmNrcNU+xnn+oK8JE5Nh0aBNvRd5AeTW1UGyTTO4tDGUBTlf8uH7it2G7nZdg==,iv:UMLZtK77JMdc8YoUsl5zktnGa2GqPUIz49V94EJPvLA=,tag:K578nsWSSiFc3XFZ0ufuSg==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:J0mlg0Y=,iv:xDKaGDypt7Dq/6OTRy0v8aREE4zD6zquq0eSilZlR4Y=,tag:nIkS/Snw0MrIni3gPOs/eQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:3WoIXfvlSLo=,iv:Ssm1GDFIIYFjy0/a1cZQR1IV8gLwf2r8x53MaTfYxJI=,tag:2WAqlHdx4ROcMOOmJNaKQQ==,type:str]
    ADMIN_EMAIL: ""
    ADMIN_CPF: ""
    BREVO_API_KEY: ENC[AES256_GCM,data:L2J88Ci1ISJRGbtjrCXcr5W3h1M+47TcfE4B9qIJsaHthwr3HIuBkAYrkAc5ddQfwB76ouQLab2PyX6bTxqS6Jdrzp5zpMFrJZmEb6wTrwDh8IEpKZb9GoU=,iv:xbHRVIYgfmSkAL1EjmIAOetkTDFV913qXPQc6dK6MYw=,tag:8aYhQ+QO56zHFSeMMdJcJw==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:GfaUyQfO/jJkh+dgwWEQtlgYrgeOyiEvG7O4nzA=,iv:BExqed/SRMfIyOGk7L5oBuNogbTLno925yo60rYoo+4=,tag:g25Fsep9Cam8F/Pn2RRXIQ==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:dn1k9rjG4jnDxVHR,iv:g4Q/+sBsfUUCa04Pqqugv7Sql9ssHiph1frFSORxUNg=,tag:BorGPe10rij8F2pnZT2lGg==,type:str]
    ZAPI_INSTANCE_ID: ENC[AES256_GCM,data:n7fojMrJNzjNXd0Cr30Kyw8k4r3iMwBhn4pEHbXimh0=,iv:LyxBr8EY2RbUBsbfyl4V4UE8e7aVfQRfxli2ZX6Iyuw=,tag:s7k7TJAsDeUQlG9N5vTmiQ==,type:str]
    ZAPI_TOKEN: ENC[AES256_GCM,data:EXQb+awL5UH7XaXbngRAxRlem5LQWRV2,iv:KObZHINrJp2ZRtQcRtPTh3nIpz2pBFLSeTFOsXKHuGw=,tag:FKTQo8H/VhDKB1QG3FfHDw==,type:str]
    ZAPI_CLIENT_TOKEN: ENC[AES256_GCM,data:ZOF0bB3HA5fTysLqnz2j0p/OrB+QSFFTQ6KBF8EiB/wbbA==,iv:ta0qvuF1hKoZR+DdcvDcrTSICZF50RZ7f/VAmomSHZ4=,tag:F2zXoHKJ7k9djqbrk20Ucw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OUI3RGljcTE4eDVSallW
            SkthazJXekFYU2pEZmFCOVIrN0lDSjFQRXljClM1USt1NUI1eXQ1bXFyaWkzbTV3
            blNrT2E5YmEvQk9IMitWODlsZDltRDQKLS0tIGh2ak1Mdmx3ZllvRktTcFJLT0o2
            Q200VnVpY3NDTm8rUEZWemRjUUE5dXcKzDmFW2fa/p6uoDMD42qiYo+SFInSt8nA
            GpfDNORBKYcEArgsi1yR6OhK3QKL8sVmP2RXLlHNIoTmadWi4IRQIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zt8e5n3g6dc4962jaggnhvq37e9yge42agyqncss5fy9kd3g0g5q23p6nf
    lastmodified: "2026-10-05T16:22:45Z"
    mac: ENC[AES256_GCM,data:0e4/bBlUrlrkUgBMqkPJZ73dVavU7fL1VOf019mxRm5cauwI8Ri3t4TjjPb8CyZAMaUi1YR2439wU5TO54xUUmB8vaJy51tfEJnmlb7kVGIQp7yBi1Pf9dAGIzCeJNLC1bGvTlWL6klwVqSFYi73gsBhQe6Jw57ZeiiNErzzvS8=,iv:cJOK102yOo9268ejy0bu83dij0P+/PPSx0SePK2MAJc=,tag:3cBuC2vTausy/cJiwLq+pg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
