apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firecrawl-api
  namespace: firecrawl
spec:
  ingressClassName: traefik
  rules:
    - host: firecrawl.guiosoft.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: firecrawl-api
                port:
                  name: http
