apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-secrets
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 1m
  wait: true
  prune: true
  dependsOn:
    - name: cloudflare-namespace
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
