apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - cloudflare-namespace.yaml
  - cloudflare-secrets.yaml
  - cloudflared.yaml
  - firecrawl-namespace.yaml
  - firecrawl-secrets.yaml
  - firecrawl.yaml
  - monitoring-namespace.yaml
  - observability-helm.yaml
