apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability-helm
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 2m
  wait: true
  prune: true
  dependsOn:
    - name: monitoring-namespace
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/observability
